const qrcode = require('qrcode');
const path = require('path');
const inquirer = require('inquirer');

const promptUser = async () => {
    const answers = await inquirer.prompt([
        {
            type: 'input',
            name: 'data',
            message: "Enter the data for which you want to generate:",
            validate: (input) => input ? true : 'data cannot be empty',
        },
    ]);
    return answers.data;
};

const generateQRCode = async (data) => {
    try {
        const qrCodeImagePath = path.join(__dirname, `${data}.png`);
        await qrcode.toFile(qrCodeImagePath, data);
        console.log(`QR code generated and saved as ${qrCodeImagePath}`);
    } catch (error) {
        console.error('error generated byt Qr code',error);
    }
};

// main function
const main = async () => {
    const data = await promptUser();
    await generateQRCode(data);
};

// run the application
main();











































































































// const inquirer = require('inquirer');
// const qr = require('qr-image');
// const fs = require('fs');

// inquirer.prompt([
//     {
//     message: "Type in your URL:",
//     name:"URL",
//     },
// ])

// .then((answers) => {
//     // EXtract url from answer object
//     const url = answers.URL;

//     // generate QR code image 
//     const qr_image = qr.image(url, {type: "png"});

//     // save qr code image (as given type) jpg,jpeg,svg
//     qr_image.pipe(fs.createWriteStream("qr_code.png"));

//     // save user input as text file
//     fs.writeFile("URL.txt",url, (error) => {
//         if (error) throw err; 
//             console.log("The File has been saved...");
//     });
// })
// .catch((error) => {
//     // handle errors
//     console.error("An error occurred...",error);
// });